name = "E4STUtil"
uuid = "12abe42c-b2e7-4a68-9e37-c6d51b9b2893"
authors = ["Ethan Russell <erussell@rff.org>"]
version = "0.1.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.0"
OrderedCollections = "1"
YAML = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
